from enum import Enum


class UserRole(str, Enum):
    PATIENT = "PATIENT"
    FRONTLINE_WORKER = "FRONTLINE_WORKER"
    DOCTOR = "DOCTOR"
    FACILITY_COORDINATOR = "FACILITY_COORDINATOR"
    ADMIN = "ADMIN"


class OrganizationType(str, Enum):
    CLINIC = "CLINIC"
    PRIMARY_HEALTH_CENTER = "PRIMARY_HEALTH_CENTER"
    DISTRICT_HOSPITAL = "DISTRICT_HOSPITAL"
    DIAGNOSTIC_CENTER = "DIAGNOSTIC_CENTER"
    ADMINISTRATIVE = "ADMINISTRATIVE"


class ConsentType(str, Enum):
    REGISTRATION = "REGISTRATION"
    CARE_COORDINATION = "CARE_COORDINATION"
    DATA_SHARING = "DATA_SHARING"


class ConsentStatus(str, Enum):
    GRANTED = "GRANTED"
    REVOKED = "REVOKED"


class EncounterType(str, Enum):
    REGISTRATION = "REGISTRATION"
    TRIAGE = "TRIAGE"
    CONSULTATION = "CONSULTATION"
    DIAGNOSTIC = "DIAGNOSTIC"
    FOLLOW_UP = "FOLLOW_UP"


class EncounterStatus(str, Enum):
    PLANNED = "PLANNED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ObservationType(str, Enum):
    RESPIRATORY_RATE = "RESPIRATORY_RATE"
    SPO2 = "SPO2"
    TEMPERATURE_C = "TEMPERATURE_C"
    PULSE = "PULSE"
    BLOOD_PRESSURE_SYSTOLIC = "BLOOD_PRESSURE_SYSTOLIC"
    BLOOD_PRESSURE_DIASTOLIC = "BLOOD_PRESSURE_DIASTOLIC"


class TriageRiskLevel(str, Enum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"
    URGENT = "URGENT"


class ReferralStatus(str, Enum):
    CREATED = "CREATED"
    ACCEPTED = "ACCEPTED"
    APPOINTMENT_PENDING = "APPOINTMENT_PENDING"
    APPOINTMENT_BOOKED = "APPOINTMENT_BOOKED"
    PATIENT_NOTIFIED = "PATIENT_NOTIFIED"
    PATIENT_ARRIVED = "PATIENT_ARRIVED"
    CONSULTATION_COMPLETED = "CONSULTATION_COMPLETED"
    REFERRED_BACK = "REFERRED_BACK"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class AppointmentStatus(str, Enum):
    REQUESTED = "REQUESTED"
    CONFIRMED = "CONFIRMED"
    CHECKED_IN = "CHECKED_IN"
    IN_QUEUE = "IN_QUEUE"
    IN_CONSULTATION = "IN_CONSULTATION"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    NO_SHOW = "NO_SHOW"


class DiagnosticRequestStatus(str, Enum):
    REQUESTED = "REQUESTED"
    SCHEDULED = "SCHEDULED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class MedicationRequestStatus(str, Enum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class CarePlanStatus(str, Enum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class FollowUpStatus(str, Enum):
    PENDING = "PENDING"
    CONTACT_ATTEMPTED = "CONTACT_ATTEMPTED"
    COMPLETED = "COMPLETED"
    MISSED = "MISSED"
    ESCALATED = "ESCALATED"
    CANCELLED = "CANCELLED"


class SyncStatus(str, Enum):
    PENDING = "PENDING"
    SYNCING = "SYNCING"
    SYNCED = "SYNCED"
    FAILED = "FAILED"
    CONFLICT = "CONFLICT"


def enum_values(enum_cls: type[Enum]) -> list[str]:
    return [member.value for member in enum_cls]

